TOP = ../../..
include $(TOP)/ecc_go/build.mk

CC_NAME ?= confidential-escrow

EGO_CONFIG_FILE = $(FPC_PATH)/samples/chaincode/confidential-escrow/confidentialEscrowEnclave.json
ECC_MAIN_FILES=$(FPC_PATH)/samples/chaincode/confidential-escrow
