version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      actions-deps:
        patterns:
          - "*"

  - package-ecosystem: "gomod"
    directories:
      - "**/*"
    allow:
      - dependency-type: all
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "github.com/hyperledger/fabric*"
      - dependency-name: "github.com/hyperledger-labs/fabric*"
    groups:
      all-deps:
        update-types:
          - minor
          - patch
