// Copyright IBM Corp. All Rights Reserved.
// Copyright 2020 Intel Corporation
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.12
// source: fpc/key_dist.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CCKeyRegistrationMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// defines the context as SHA256 of cc_params
	CcParamsHash []byte `protobuf:"bytes,1,opt,name=cc_params_hash,json=ccParamsHash,proto3" json:"cc_params_hash,omitempty"`
	// public chaincode encryption key
	ChaincodeEk []byte `protobuf:"bytes,2,opt,name=chaincode_ek,json=chaincodeEk,proto3" json:"chaincode_ek,omitempty"`
	// creator of this message
	// enclave_id is the SHA256 hash of enclave_vk
	EnclaveId []byte `protobuf:"bytes,3,opt,name=enclave_id,json=enclaveId,proto3" json:"enclave_id,omitempty"`
}

func (x *CCKeyRegistrationMessage) Reset() {
	*x = CCKeyRegistrationMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fpc_key_dist_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CCKeyRegistrationMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CCKeyRegistrationMessage) ProtoMessage() {}

func (x *CCKeyRegistrationMessage) ProtoReflect() protoreflect.Message {
	mi := &file_fpc_key_dist_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CCKeyRegistrationMessage.ProtoReflect.Descriptor instead.
func (*CCKeyRegistrationMessage) Descriptor() ([]byte, []int) {
	return file_fpc_key_dist_proto_rawDescGZIP(), []int{0}
}

func (x *CCKeyRegistrationMessage) GetCcParamsHash() []byte {
	if x != nil {
		return x.CcParamsHash
	}
	return nil
}

func (x *CCKeyRegistrationMessage) GetChaincodeEk() []byte {
	if x != nil {
		return x.ChaincodeEk
	}
	return nil
}

func (x *CCKeyRegistrationMessage) GetEnclaveId() []byte {
	if x != nil {
		return x.EnclaveId
	}
	return nil
}

type SignedCCKeyRegistrationMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// serialization of type CCKeyRegistrationMessage
	SerializedCckeyRegMsg *anypb.Any `protobuf:"bytes,1,opt,name=serialized_cckey_reg_msg,json=serializedCckeyRegMsg,proto3" json:"serialized_cckey_reg_msg,omitempty"`
	// signature of the message creator (enclave)
	Signature []byte `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (x *SignedCCKeyRegistrationMessage) Reset() {
	*x = SignedCCKeyRegistrationMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fpc_key_dist_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SignedCCKeyRegistrationMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignedCCKeyRegistrationMessage) ProtoMessage() {}

func (x *SignedCCKeyRegistrationMessage) ProtoReflect() protoreflect.Message {
	mi := &file_fpc_key_dist_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignedCCKeyRegistrationMessage.ProtoReflect.Descriptor instead.
func (*SignedCCKeyRegistrationMessage) Descriptor() ([]byte, []int) {
	return file_fpc_key_dist_proto_rawDescGZIP(), []int{1}
}

func (x *SignedCCKeyRegistrationMessage) GetSerializedCckeyRegMsg() *anypb.Any {
	if x != nil {
		return x.SerializedCckeyRegMsg
	}
	return nil
}

func (x *SignedCCKeyRegistrationMessage) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type ExportMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// defines the context of this export message as SHA256 of cc_params
	CcParamsHash []byte `protobuf:"bytes,1,opt,name=cc_params_hash,json=ccParamsHash,proto3" json:"cc_params_hash,omitempty"`
	// public chaincode encryption key
	ChaincodeEk []byte `protobuf:"bytes,2,opt,name=chaincode_ek,json=chaincodeEk,proto3" json:"chaincode_ek,omitempty"`
	// chaincode keys encrypted for the receiver
	CckeysEnc []byte `protobuf:"bytes,3,opt,name=cckeys_enc,json=cckeysEnc,proto3" json:"cckeys_enc,omitempty"`
	// receiver of this export message
	ReceiverEnclaveVk []byte `protobuf:"bytes,4,opt,name=receiver_enclave_vk,json=receiverEnclaveVk,proto3" json:"receiver_enclave_vk,omitempty"`
	// sender (creator) of this export message
	SenderEnclaveVk []byte `protobuf:"bytes,5,opt,name=sender_enclave_vk,json=senderEnclaveVk,proto3" json:"sender_enclave_vk,omitempty"`
}

func (x *ExportMessage) Reset() {
	*x = ExportMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fpc_key_dist_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExportMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportMessage) ProtoMessage() {}

func (x *ExportMessage) ProtoReflect() protoreflect.Message {
	mi := &file_fpc_key_dist_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportMessage.ProtoReflect.Descriptor instead.
func (*ExportMessage) Descriptor() ([]byte, []int) {
	return file_fpc_key_dist_proto_rawDescGZIP(), []int{2}
}

func (x *ExportMessage) GetCcParamsHash() []byte {
	if x != nil {
		return x.CcParamsHash
	}
	return nil
}

func (x *ExportMessage) GetChaincodeEk() []byte {
	if x != nil {
		return x.ChaincodeEk
	}
	return nil
}

func (x *ExportMessage) GetCckeysEnc() []byte {
	if x != nil {
		return x.CckeysEnc
	}
	return nil
}

func (x *ExportMessage) GetReceiverEnclaveVk() []byte {
	if x != nil {
		return x.ReceiverEnclaveVk
	}
	return nil
}

func (x *ExportMessage) GetSenderEnclaveVk() []byte {
	if x != nil {
		return x.SenderEnclaveVk
	}
	return nil
}

type SignedExportMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// serialization of type ExportMessage
	SerializedExportMsgBytes *anypb.Any `protobuf:"bytes,1,opt,name=serialized_export_msg_bytes,json=serializedExportMsgBytes,proto3" json:"serialized_export_msg_bytes,omitempty"`
	// signature of the message creator
	Signature []byte `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (x *SignedExportMessage) Reset() {
	*x = SignedExportMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fpc_key_dist_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SignedExportMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignedExportMessage) ProtoMessage() {}

func (x *SignedExportMessage) ProtoReflect() protoreflect.Message {
	mi := &file_fpc_key_dist_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignedExportMessage.ProtoReflect.Descriptor instead.
func (*SignedExportMessage) Descriptor() ([]byte, []int) {
	return file_fpc_key_dist_proto_rawDescGZIP(), []int{3}
}

func (x *SignedExportMessage) GetSerializedExportMsgBytes() *anypb.Any {
	if x != nil {
		return x.SerializedExportMsgBytes
	}
	return nil
}

func (x *SignedExportMessage) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

var File_fpc_key_dist_proto protoreflect.FileDescriptor

var file_fpc_key_dist_proto_rawDesc = []byte{
	0x0a, 0x12, 0x66, 0x70, 0x63, 0x2f, 0x6b, 0x65, 0x79, 0x5f, 0x64, 0x69, 0x73, 0x74, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10, 0x6b, 0x65, 0x79, 0x5f, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69,
	0x62, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x19, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x61, 0x6e, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x82, 0x01, 0x0a, 0x18, 0x43, 0x43, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x67, 0x69, 0x73,
	0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x24,
	0x0a, 0x0e, 0x63, 0x63, 0x5f, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x5f, 0x68, 0x61, 0x73, 0x68,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0c, 0x63, 0x63, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73,
	0x48, 0x61, 0x73, 0x68, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x63, 0x6f, 0x64,
	0x65, 0x5f, 0x65, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0b, 0x63, 0x68, 0x61, 0x69,
	0x6e, 0x63, 0x6f, 0x64, 0x65, 0x45, 0x6b, 0x12, 0x1d, 0x0a, 0x0a, 0x65, 0x6e, 0x63, 0x6c, 0x61,
	0x76, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x65, 0x6e, 0x63,
	0x6c, 0x61, 0x76, 0x65, 0x49, 0x64, 0x22, 0x8d, 0x01, 0x0a, 0x1e, 0x53, 0x69, 0x67, 0x6e, 0x65,
	0x64, 0x43, 0x43, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x4d, 0x0a, 0x18, 0x73, 0x65, 0x72,
	0x69, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x64, 0x5f, 0x63, 0x63, 0x6b, 0x65, 0x79, 0x5f, 0x72, 0x65,
	0x67, 0x5f, 0x6d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e,
	0x79, 0x52, 0x15, 0x73, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x64, 0x43, 0x63, 0x6b,
	0x65, 0x79, 0x52, 0x65, 0x67, 0x4d, 0x73, 0x67, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x69, 0x67, 0x6e,
	0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x73, 0x69, 0x67,
	0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x22, 0xd3, 0x01, 0x0a, 0x0d, 0x45, 0x78, 0x70, 0x6f, 0x72,
	0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x24, 0x0a, 0x0e, 0x63, 0x63, 0x5f, 0x70,
	0x61, 0x72, 0x61, 0x6d, 0x73, 0x5f, 0x68, 0x61, 0x73, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x0c, 0x63, 0x63, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x48, 0x61, 0x73, 0x68, 0x12, 0x21,
	0x0a, 0x0c, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x5f, 0x65, 0x6b, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x0b, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x45,
	0x6b, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x63, 0x6b, 0x65, 0x79, 0x73, 0x5f, 0x65, 0x6e, 0x63, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x63, 0x63, 0x6b, 0x65, 0x79, 0x73, 0x45, 0x6e, 0x63,
	0x12, 0x2e, 0x0a, 0x13, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x5f, 0x65, 0x6e, 0x63,
	0x6c, 0x61, 0x76, 0x65, 0x5f, 0x76, 0x6b, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x11, 0x72,
	0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x45, 0x6e, 0x63, 0x6c, 0x61, 0x76, 0x65, 0x56, 0x6b,
	0x12, 0x2a, 0x0a, 0x11, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x5f, 0x65, 0x6e, 0x63, 0x6c, 0x61,
	0x76, 0x65, 0x5f, 0x76, 0x6b, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0f, 0x73, 0x65, 0x6e,
	0x64, 0x65, 0x72, 0x45, 0x6e, 0x63, 0x6c, 0x61, 0x76, 0x65, 0x56, 0x6b, 0x22, 0x88, 0x01, 0x0a,
	0x13, 0x53, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x45, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x12, 0x53, 0x0a, 0x1b, 0x73, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x69, 0x7a,
	0x65, 0x64, 0x5f, 0x65, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x5f, 0x6d, 0x73, 0x67, 0x5f, 0x62, 0x79,
	0x74, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52,
	0x18, 0x73, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x64, 0x45, 0x78, 0x70, 0x6f, 0x72,
	0x74, 0x4d, 0x73, 0x67, 0x42, 0x79, 0x74, 0x65, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x69, 0x67,
	0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x73, 0x69,
	0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x42, 0x41, 0x5a, 0x3f, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x68, 0x79, 0x70, 0x65, 0x72, 0x6c, 0x65, 0x64, 0x67, 0x65,
	0x72, 0x2f, 0x66, 0x61, 0x62, 0x72, 0x69, 0x63, 0x2d, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65,
	0x2d, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72,
	0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_fpc_key_dist_proto_rawDescOnce sync.Once
	file_fpc_key_dist_proto_rawDescData = file_fpc_key_dist_proto_rawDesc
)

func file_fpc_key_dist_proto_rawDescGZIP() []byte {
	file_fpc_key_dist_proto_rawDescOnce.Do(func() {
		file_fpc_key_dist_proto_rawDescData = protoimpl.X.CompressGZIP(file_fpc_key_dist_proto_rawDescData)
	})
	return file_fpc_key_dist_proto_rawDescData
}

var file_fpc_key_dist_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_fpc_key_dist_proto_goTypes = []interface{}{
	(*CCKeyRegistrationMessage)(nil),       // 0: key_distribution.CCKeyRegistrationMessage
	(*SignedCCKeyRegistrationMessage)(nil), // 1: key_distribution.SignedCCKeyRegistrationMessage
	(*ExportMessage)(nil),                  // 2: key_distribution.ExportMessage
	(*SignedExportMessage)(nil),            // 3: key_distribution.SignedExportMessage
	(*anypb.Any)(nil),                      // 4: google.protobuf.Any
}
var file_fpc_key_dist_proto_depIdxs = []int32{
	4, // 0: key_distribution.SignedCCKeyRegistrationMessage.serialized_cckey_reg_msg:type_name -> google.protobuf.Any
	4, // 1: key_distribution.SignedExportMessage.serialized_export_msg_bytes:type_name -> google.protobuf.Any
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_fpc_key_dist_proto_init() }
func file_fpc_key_dist_proto_init() {
	if File_fpc_key_dist_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_fpc_key_dist_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CCKeyRegistrationMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fpc_key_dist_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SignedCCKeyRegistrationMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fpc_key_dist_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExportMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fpc_key_dist_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SignedExportMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_fpc_key_dist_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_fpc_key_dist_proto_goTypes,
		DependencyIndexes: file_fpc_key_dist_proto_depIdxs,
		MessageInfos:      file_fpc_key_dist_proto_msgTypes,
	}.Build()
	File_fpc_key_dist_proto = out.File
	file_fpc_key_dist_proto_rawDesc = nil
	file_fpc_key_dist_proto_goTypes = nil
	file_fpc_key_dist_proto_depIdxs = nil
}
