// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"sync"
)

type PolicyEvaluator struct {
	EvaluateCreatorIdentityStub        func([]byte, []byte) error
	evaluateCreatorIdentityMutex       sync.RWMutex
	evaluateCreatorIdentityArgsForCall []struct {
		arg1 []byte
		arg2 []byte
	}
	evaluateCreatorIdentityReturns struct {
		result1 error
	}
	evaluateCreatorIdentityReturnsOnCall map[int]struct {
		result1 error
	}
	EvaluateIdentityStub        func([]byte, []byte) error
	evaluateIdentityMutex       sync.RWMutex
	evaluateIdentityArgsForCall []struct {
		arg1 []byte
		arg2 []byte
	}
	evaluateIdentityReturns struct {
		result1 error
	}
	evaluateIdentityReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *PolicyEvaluator) EvaluateCreatorIdentity(arg1 []byte, arg2 []byte) error {
	var arg1Copy []byte
	if arg1 != nil {
		arg1Copy = make([]byte, len(arg1))
		copy(arg1Copy, arg1)
	}
	var arg2Copy []byte
	if arg2 != nil {
		arg2Copy = make([]byte, len(arg2))
		copy(arg2Copy, arg2)
	}
	fake.evaluateCreatorIdentityMutex.Lock()
	ret, specificReturn := fake.evaluateCreatorIdentityReturnsOnCall[len(fake.evaluateCreatorIdentityArgsForCall)]
	fake.evaluateCreatorIdentityArgsForCall = append(fake.evaluateCreatorIdentityArgsForCall, struct {
		arg1 []byte
		arg2 []byte
	}{arg1Copy, arg2Copy})
	fake.recordInvocation("EvaluateCreatorIdentity", []interface{}{arg1Copy, arg2Copy})
	fake.evaluateCreatorIdentityMutex.Unlock()
	if fake.EvaluateCreatorIdentityStub != nil {
		return fake.EvaluateCreatorIdentityStub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	fakeReturns := fake.evaluateCreatorIdentityReturns
	return fakeReturns.result1
}

func (fake *PolicyEvaluator) EvaluateCreatorIdentityCallCount() int {
	fake.evaluateCreatorIdentityMutex.RLock()
	defer fake.evaluateCreatorIdentityMutex.RUnlock()
	return len(fake.evaluateCreatorIdentityArgsForCall)
}

func (fake *PolicyEvaluator) EvaluateCreatorIdentityCalls(stub func([]byte, []byte) error) {
	fake.evaluateCreatorIdentityMutex.Lock()
	defer fake.evaluateCreatorIdentityMutex.Unlock()
	fake.EvaluateCreatorIdentityStub = stub
}

func (fake *PolicyEvaluator) EvaluateCreatorIdentityArgsForCall(i int) ([]byte, []byte) {
	fake.evaluateCreatorIdentityMutex.RLock()
	defer fake.evaluateCreatorIdentityMutex.RUnlock()
	argsForCall := fake.evaluateCreatorIdentityArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *PolicyEvaluator) EvaluateCreatorIdentityReturns(result1 error) {
	fake.evaluateCreatorIdentityMutex.Lock()
	defer fake.evaluateCreatorIdentityMutex.Unlock()
	fake.EvaluateCreatorIdentityStub = nil
	fake.evaluateCreatorIdentityReturns = struct {
		result1 error
	}{result1}
}

func (fake *PolicyEvaluator) EvaluateCreatorIdentityReturnsOnCall(i int, result1 error) {
	fake.evaluateCreatorIdentityMutex.Lock()
	defer fake.evaluateCreatorIdentityMutex.Unlock()
	fake.EvaluateCreatorIdentityStub = nil
	if fake.evaluateCreatorIdentityReturnsOnCall == nil {
		fake.evaluateCreatorIdentityReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.evaluateCreatorIdentityReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *PolicyEvaluator) EvaluateIdentity(arg1 []byte, arg2 []byte) error {
	var arg1Copy []byte
	if arg1 != nil {
		arg1Copy = make([]byte, len(arg1))
		copy(arg1Copy, arg1)
	}
	var arg2Copy []byte
	if arg2 != nil {
		arg2Copy = make([]byte, len(arg2))
		copy(arg2Copy, arg2)
	}
	fake.evaluateIdentityMutex.Lock()
	ret, specificReturn := fake.evaluateIdentityReturnsOnCall[len(fake.evaluateIdentityArgsForCall)]
	fake.evaluateIdentityArgsForCall = append(fake.evaluateIdentityArgsForCall, struct {
		arg1 []byte
		arg2 []byte
	}{arg1Copy, arg2Copy})
	fake.recordInvocation("EvaluateIdentity", []interface{}{arg1Copy, arg2Copy})
	fake.evaluateIdentityMutex.Unlock()
	if fake.EvaluateIdentityStub != nil {
		return fake.EvaluateIdentityStub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	fakeReturns := fake.evaluateIdentityReturns
	return fakeReturns.result1
}

func (fake *PolicyEvaluator) EvaluateIdentityCallCount() int {
	fake.evaluateIdentityMutex.RLock()
	defer fake.evaluateIdentityMutex.RUnlock()
	return len(fake.evaluateIdentityArgsForCall)
}

func (fake *PolicyEvaluator) EvaluateIdentityCalls(stub func([]byte, []byte) error) {
	fake.evaluateIdentityMutex.Lock()
	defer fake.evaluateIdentityMutex.Unlock()
	fake.EvaluateIdentityStub = stub
}

func (fake *PolicyEvaluator) EvaluateIdentityArgsForCall(i int) ([]byte, []byte) {
	fake.evaluateIdentityMutex.RLock()
	defer fake.evaluateIdentityMutex.RUnlock()
	argsForCall := fake.evaluateIdentityArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *PolicyEvaluator) EvaluateIdentityReturns(result1 error) {
	fake.evaluateIdentityMutex.Lock()
	defer fake.evaluateIdentityMutex.Unlock()
	fake.EvaluateIdentityStub = nil
	fake.evaluateIdentityReturns = struct {
		result1 error
	}{result1}
}

func (fake *PolicyEvaluator) EvaluateIdentityReturnsOnCall(i int, result1 error) {
	fake.evaluateIdentityMutex.Lock()
	defer fake.evaluateIdentityMutex.Unlock()
	fake.EvaluateIdentityStub = nil
	if fake.evaluateIdentityReturnsOnCall == nil {
		fake.evaluateIdentityReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.evaluateIdentityReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *PolicyEvaluator) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.evaluateCreatorIdentityMutex.RLock()
	defer fake.evaluateCreatorIdentityMutex.RUnlock()
	fake.evaluateIdentityMutex.RLock()
	defer fake.evaluateIdentityMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *PolicyEvaluator) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}
