// Code generated by counterfeiter. DO NOT EDIT.
package fakes

import (
	"sync"

	"github.com/hyperledger/fabric-private-chaincode/client_sdk/go/pkg/gateway"
)

type Network struct {
	GetContractStub        func(id string) gateway.Contract
	getContractMutex       sync.RWMutex
	getContractArgsForCall []struct {
		id string
	}
	getContractReturns struct {
		result1 gateway.Contract
	}
	getContractReturnsOnCall map[int]struct {
		result1 gateway.Contract
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *Network) GetContract(id string) gateway.Contract {
	fake.getContractMutex.Lock()
	ret, specificReturn := fake.getContractReturnsOnCall[len(fake.getContractArgsForCall)]
	fake.getContractArgsForCall = append(fake.getContractArgsForCall, struct {
		id string
	}{id})
	fake.recordInvocation("GetContract", []interface{}{id})
	fake.getContractMutex.Unlock()
	if fake.GetContractStub != nil {
		return fake.GetContractStub(id)
	}
	if specificReturn {
		return ret.result1
	}
	return fake.getContractReturns.result1
}

func (fake *Network) GetContractCallCount() int {
	fake.getContractMutex.RLock()
	defer fake.getContractMutex.RUnlock()
	return len(fake.getContractArgsForCall)
}

func (fake *Network) GetContractArgsForCall(i int) string {
	fake.getContractMutex.RLock()
	defer fake.getContractMutex.RUnlock()
	return fake.getContractArgsForCall[i].id
}

func (fake *Network) GetContractReturns(result1 gateway.Contract) {
	fake.GetContractStub = nil
	fake.getContractReturns = struct {
		result1 gateway.Contract
	}{result1}
}

func (fake *Network) GetContractReturnsOnCall(i int, result1 gateway.Contract) {
	fake.GetContractStub = nil
	if fake.getContractReturnsOnCall == nil {
		fake.getContractReturnsOnCall = make(map[int]struct {
			result1 gateway.Contract
		})
	}
	fake.getContractReturnsOnCall[i] = struct {
		result1 gateway.Contract
	}{result1}
}

func (fake *Network) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.getContractMutex.RLock()
	defer fake.getContractMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *Network) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}
