# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0

FROM hyperledger/fabric-private-chaincode-ccenv:latest

COPY fpcclient /usr/local/bin

WORKDIR /opt/gopath/src/github.com/hyperledger/fabric/peer
