# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ca-org3
  name: ca-org3
  namespace: hyperledger
spec:
  selector:
    matchLabels:
      app: ca-org3
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ca-org3
    spec:
      containers:
        - args:
            - sh
            - -c
            - fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.org3-cert.pem
              --ca.keyfile /etc/hyperledger/fabric-ca-server-config/priv_sk
              -b admin:adminpw -d
          env:
            - name: FABRIC_CA_HOME
              value: /etc/hyperledger/fabric-ca-server
            - name: FABRIC_CA_SERVER_CA_NAME
              value: ca-org3
            - name: FABRIC_CA_SERVER_TLS_CERTFILE
              value: /etc/hyperledger/fabric-ca-server-config/ca.org3-cert.pem
            - name: FABRIC_CA_SERVER_TLS_ENABLED
              value: "true"
            - name: FABRIC_CA_SERVER_TLS_KEYFILE
              value: /etc/hyperledger/fabric-ca-server-config/priv_sk
          image: hyperledger/fabric-ca:1.5.12
          name: ca-org3
          ports:
            - containerPort: 7054
          volumeMounts:
            - mountPath: /etc/hyperledger/fabric-ca-server-config
              name: ca-org3-claim0
              readOnly: true
      restartPolicy: Always
      volumes:
        - name: ca-org3-claim0
          hostPath:
            path: /fpc/samples/deployment/k8s/crypto-config/peerOrganizations/org3/ca/
            type: Directory
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ca-org3
  name: ca-org3
  namespace: hyperledger
spec:
  type: ClusterIP
  ports:
    - name: "https"
      port: 7054
      targetPort: 7054
  selector:
    app: ca-org3

