# Copyright Intel Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0

TOP = ..
include $(TOP)/build.mk

all: test

test: auction_test echo_test

auction_test:
	./auction_test.sh

echo_test:
	./echo_test.sh
