# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0

ARG BOILERPLATE_EXTENSION
ARG FPC_VERSION=latest

FROM hyperledger/fabric-private-chaincode-boilerplate-ecc${BOILERPLATE_EXTENSION}:${FPC_VERSION}

ARG enclave_so_path
ARG CC_PATH="/usr/local/bin"
ARG CC_LIB_PATH=${CC_PATH}"/enclave/lib"

RUN test -n "$enclave_so_path" 

copy ${enclave_so_path}/enclave.signed.so ${CC_LIB_PATH}/

copy ${enclave_so_path}/mrenclave ${CC_PATH}/
